### ISSUE TITLE
请问升级到webpack4，每次修改页面reload报错的问题解决了吗？

### ISSUE THREAD

**Issue by Realybig** [hzsrc/vue-element-ui-scaffold-webpack4#9]
本地调试的时候每次修改完文件都会报错，看代码是reload的时候报错的，不知道是不是插件更新了，api更换了。。。
```
TypeError: cb is not a function
    at /Users/labs/webpack/office/build/dev-server.js:39:9
    at Promise (eval at create (/Users/labs/webpack/office/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:17:16)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/Users/labs/webpack/office/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/labs/webpack/office/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/labs/webpack/office/node_modules/html-webpack-plugin/index.js:673:47
    at Promise.resolve.then.then.then.then.then.then.then.then.catch.then.then (/Users/labs/webpack/office/node_modules/html-webpack-plugin/index.js:214:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```
// dev-server.js
var hotMiddleware = require('webpack-hot-middleware')(compiler, {
    log: () => {}
});
// force page reload when html-webpack-plugin template changes
compiler.plugin('compilation', function (compilation) {
    compilation.plugin('html-webpack-plugin-after-emit', function (data, cb) {
        console.log('html-webpack-plugin-after-emit', data, cb)
        hotMiddleware.publish({ action: 'reload' });
        cb();
    });
});
```

**Comment by LiZheGuang** [comment]
解决了吗

**Comment by hzsrc** [comment]
你这代码不是这个项目的吧，把这个项目拉下来试一下呢？很久前就没这个问题了
